# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.79.1'

      # Runs a set of commands using the runners shell
      - name: Build Hugo
        run: |
          hugo --source exampleSite --themesDir ../../ --baseURL https://owlcode.github.io/hugo-owlminimal/
          
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.OWL_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: exampleSite/public # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
